# --- starship prompt config file ----------------------------------------------

# @see "https://starship.rs/config/#prompt"

# --- performance issues -------------------------------------------------------

# - if there are performance issues, remove the following line
#   $git_status\
# - if performance issues have been addressed, the following line should appear after $git_state
#   $git_status\

# --- options ------------------------------------------------------------------

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

# Wait 500 milliseconds for commands to finish running
command_timeout = 500

# Enable the blank line at the start of the prompt
add_newline = true

# --- prompt format ------------------------------------------------------------

format = """
$username\
$hostname\
$shlvl\
$kubernetes\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$hg_branch\
$docker_context\
$package\
$cmake\
$dart\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$helm\
$java\
$julia\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$purescript\
$python\
$ruby\
$rust\
$swift\
$terraform\
$zig\
$nix_shell\
$conda\
$memory_usage\
$aws\
$gcloud\
$env_var\
$crystal\
$custom\
$cmd_duration\
$line_break\
$jobs\
$battery\
$time\
$status\
$character"""

# --- prompt overrides and additions -------------------------------------------

[username]
format = "[$user]($style)"
disabled = false
show_always = true

[hostname]
ssh_only = false
format = "@[$hostname](bold green) "

[directory]
truncate_to_repo = true
truncation_length = 3
truncation_symbol = "…/"

[java]
symbol = " "
style = "red"

[custom.docker1]
description = "The Docker base image used in this project"
command = "rg --case-sensitive --no-line-number '^FROM' docker/Dockerfile | cut -d':' -f1 | cut -d' ' -f2"
directories = ["docker"]
symbol = " "
style = "blue"

[custom.docker2]
description = "The Docker base image used in this project"
command = "rg --case-sensitive --no-line-number '^FROM' Dockerfile | cut -d':' -f1 | cut -d' ' -f2"
files = ["Dockerfile"]
symbol = " "
style = "blue"

[custom.grails]
description = "The version of Grails used in this project"
command = "rg --case-sensitive --no-heading --no-messages --no-line-number grailsVersion gradle.properties | cut -d'=' -f2"
files = ["grailsw", "gradle.properties"]
symbol = " v"
style = "green"

[custom.git]
description = "The project name for git projects"
command = "basename `git rev-parse --show-toplevel`"
when = "git rev-parse --show-toplevel"
os = "linux"
format = "in [$symbol($output )]($style)"
symbol = " "
style = "bold fg:208"

[time]
disabled = false

