# --- starship prompt config file ----------------------------------------------

# @see "https://starship.rs/config/#prompt"

# --- performance issues -------------------------------------------------------

# - if there are performance issues, remove the following line
#   $git_status\
# - if performance issues have been addressed, the following line should appear after $git_state
#   $git_status\

# --- prompt format ------------------------------------------------------------

format = """
$username\
$hostname\
$shlvl\
$kubernetes\
$directory\
$git_branch\
$git_commit\
$git_state\
$hg_branch\
$docker_context\
$package\
$cmake\
$dart\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$helm\
$java\
$julia\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$purescript\
$python\
$ruby\
$rust\
$swift\
$terraform\
$zig\
$nix_shell\
$conda\
$memory_usage\
$aws\
$gcloud\
$env_var\
$crystal\
$custom\
$cmd_duration\
$line_break\
$jobs\
$battery\
$time\
$status\
$character"""

# --- prompt overrides and additions -------------------------------------------

[java]
symbol = " "
style = "red"

[custom.docker]
description = "The Docker base image used in this project"
command = "rg FROM docker/Dockerfile | cut -d':' -f1 | cut -d'/' -f2"
directories = ["docker"]
symbol = "🐳 "
style = "blue"

[custom.grails]
description = "The version of Grails used in this project"
command = "rg grailsVersion gradle.properties | cut -d'=' -f2"
files = ["grailsw", "gradle.properties"]
symbol = " v"
style = "green"

[time]
disabled = false

