#!/bin/zsh

# The Zsh Starter Kit allows you to replace the curated plugins list it
# ships with with a custom one by creating a file named .zgen-local-plugins.
#
# This is to make it easier to customize without having to maintain a separate
# fork of the starter kit.

ZGEN_LOADED=()
ZGEN_COMPLETIONS=()

# Load me last
GENCOMPL_FPATH=$HOME/.zsh/complete

# ohmyzsh plugins {{{

zgen ohmyzsh

# ohmyzsh plugins
zgen ohmyzsh plugins/bgnotify
zgen ohmyzsh plugins/colored-man-pages
zgen ohmyzsh plugins/colorize
zgen ohmyzsh plugins/command-not-found
zgen ohmyzsh plugins/docker
zgen ohmyzsh plugins/docker-compose
zgen ohmyzsh plugins/extract
zgen ohmyzsh plugins/git
# zgen ohmyzsh plugins/git-extras
zgen ohmyzsh plugins/github
zgen ohmyzsh plugins/gradle
zgen ohmyzsh plugins/last-working-dir
# zgen ohmyzsh plugins/per-directory-history
zgen ohmyzsh plugins/pip
zgen ohmyzsh plugins/python
zgen ohmyzsh plugins/rsync
zgen ohmyzsh plugins/sudo
zgen ohmyzsh plugins/vagrant
zgen ohmyzsh plugins/wd
# zgen ohmyzsh plugins/z
zgen ohmyzsh plugins/zsh-navigation-tools
zgen ohmyzsh plugins/zsh_reload

# end ohmyzsh plugins }}}

# other plugins {{{

# notes:
# - load syntax-highlighting before history-substring-search
# - load fz after z

# unused, but possibly worthwhile...
# - jeffreytse/zsh-vi-mode
# - changyuheng/fz
# - marlonrichert/zsh-autocomplete
# - rimraf/k
# - romkatv/powerlevel10k powerlevel10k
# - rupa/z
# - unixorn/autoupdate-zgen
# - unixorn/zsh-quickstart-kit

# bulk load other zsh plugins
zgen loadall <<EOPLUGINS
  chrissicool/zsh-256color
  djui/alias-tips
  gradle/gradle-completion
  mafredri/zsh-async
  nobeans/zsh-sdkman
  RobSis/zsh-completion-generator
  skx/sysadmin-util
  unixorn/fzf-zsh-plugin
  unixorn/git-extra-commands
  unixorn/jpb.zshplugin
  zsh-users/zsh-autosuggestions
  zsh-users/zsh-completions src
  zsh-users/zsh-syntax-highlighting
  zsh-users/zsh-history-substring-search
EOPLUGINS
# ^ can't indent this EOPLUGINS

# end other plugins }}}

# Save it all to init script
zgen save

#
# vim: set ft=zsh fdm=marker:
