#!/bin/zsh

# The Zsh Starter Kit allows you to replace the curated plugins list it
# ships with with a custom one by creating a file named .zgen-local-plugins.
#
# This is to make it easier to customize without having to maintain a separate
# fork of the starter kit.

ZGEN_LOADED=()
ZGEN_COMPLETIONS=()

# Load me last
GENCOMPL_FPATH=$HOME/.zsh/complete

# zgen plugins {{{

zgen oh-my-zsh

# oh-my-zsh plugins
zgen oh-my-zsh plugins/bgnotify
zgen oh-my-zsh plugins/colored-man-pages
zgen oh-my-zsh plugins/colorize
zgen oh-my-zsh plugins/command-not-found
zgen oh-my-zsh plugins/docker
zgen oh-my-zsh plugins/docker-compose
zgen oh-my-zsh plugins/extract
zgen oh-my-zsh plugins/git
# zgen oh-my-zsh plugins/git-extras
zgen oh-my-zsh plugins/github
zgen oh-my-zsh plugins/gradle
zgen oh-my-zsh plugins/last-working-dir
# zgen oh-my-zsh plugins/per-directory-history
zgen oh-my-zsh plugins/pip
zgen oh-my-zsh plugins/python
zgen oh-my-zsh plugins/rsync
zgen oh-my-zsh plugins/sudo
zgen oh-my-zsh plugins/vagrant
zgen oh-my-zsh plugins/wd
# zgen oh-my-zsh plugins/z
zgen oh-my-zsh plugins/zsh-navigation-tools
zgen oh-my-zsh plugins/zsh_reload

# bulk load plugins
# notes:
# - load syntax-highlighting before history-substring-search
# - load fz after z
# no longer used...
# - marlonrichert/zsh-autocomplete
# - changyuheng/fz
# - rupa/z
# - rimraf/k
# - romkatv/powerlevel10k powerlevel10k
zgen loadall <<EOPLUGINS
  chrissicool/zsh-256color
  gradle/gradle-completion
  mafredri/zsh-async
  nobeans/zsh-sdkman
  RobSis/zsh-completion-generator
  skx/sysadmin-util
  unixorn/autoupdate-zgen
  unixorn/git-extra-commands
  unixorn/jpb.zshplugin
  zsh-users/zsh-autosuggestions
  zsh-users/zsh-completions src
  zsh-users/zsh-syntax-highlighting
  zsh-users/zsh-history-substring-search
EOPLUGINS
# ^ can't indent this EOPLUGINS

# Save it all to init script
zgen save

# end zgen plugins }}}

#
# vim: set ft=zsh fdm=marker:
