# motd {{{
#

/usr/bin/lsb_release -s -d
/usr/lib/update-notifier/apt-check --human-readable
/usr/lib/ubuntu-release-upgrader/check-new-release -q

#
# end motd }}}

auto-ls () { /bin/ls -CF } #  --classify; }
chpwd_functions=( auto-ls $chpwd_functions )

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
