# .zshrc

# zgen {{{
#

if [ -f ~/.zgen-setup ]; then
  source ~/.zgen-setup
fi

#
# end zgen }}}

# environment variables {{{
#

# paranoid file permissions
#umask 007

# less paranoid file permissions
umask 002

# locale settings
# using "C" is useful for expected sorting of filenames
# export LC_ALL="C.UTF-8"  # use this for foreign character support
# export LC_ALL="C"        # use this if the next commands do not work...
#
# Enforce correct locales from the beginning:
# LC_ALL is unset since it overwrites everything
# LANG=en_US.UTF-8 is used, except for:
# LC_COLLATE=C   C-language conventions are used for sorting
# LC_MESSAGES=C  never translates program output
# LC_TIME=en_DK  produces yyyy-mm-dd hh:mm date/time output
#unset LC_ALL
export LANGUAGE="en_US.UTF-8"
export LANG="en_US.UTF-8"
export LC_CTYPE="en_US.UTF-8"
export LC_COLLATE="C"
export LC_MESSAGES="C"
export LC_TIME="en_DK.UTF-8"

# settings for 'less'
# export PAGER='$HOME/bin/less.sh'
export PAGER='/usr/bin/less'
export LESS="-EiMRX"  # LESS="-M"
#export LESSOPEN="|/usr/local/bin/lesspipe.sh %s"
export LESSOPEN="|$HOME/bin/lesspipe.sh %s"

# programming languages
export GOPATH=$HOME/gocode
# export JAVA_HOME=$HOME/java/jdk17

# common variables
export PATH=$HOME/.npm-global/bin:$HOME/bin:$GOPATH/bin:$PATH
export EDITOR='/usr/bin/nvim'  # '/usr/bin/vim'
export USE_EDITOR=$EDITOR
export VISUAL=$EDITOR

# zsh variables
export DISABLE_CORRECTION="true"
export COMPLETION_WAITING_DOTS="true"
export UPDATE_ZSH_DAYS=1
export HISTIGNORE="&:ls:[bf]g:exit:reset:clear:cd:cd .."
export HISTSIZE=25000
export SAVEHIST=10000

#
# end environment variables }}}

# other settings {{{
#

# zsh options; @see http://zsh.sourceforge.net/Doc/Release/Options.html
setopt append_history
setopt extended_history
setopt hist_expire_dups_first
setopt hist_ignore_all_dups
setopt hist_ignore_dups
setopt hist_ignore_space
setopt hist_reduce_blanks
setopt hist_save_no_dups
setopt hist_verify
# setopt noclobber
setopt rm_star_wait
setopt share_history
# setopt inc_append_history_time

# enable debugging (useful for declare/typeset builtins)
# shopt extdebug > /dev/null || shopt -s extdebug

autoload -U compinit
compinit

# vi-mode
bindkey -v

#
# end other settings }}}

# aliases, functions, and themes {{{
#

source $HOME/dotfiles/zsh/aliases.zsh
source $HOME/dotfiles/zsh/functions.zsh
source $HOME/dotfiles/zsh/my.zsh-theme

#
# end aliases, functions, and themes }}}

# other programs' settings {{{
# may be appended to the end of this file
#

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"

#
# }}}

#
# vim: set ft=zsh fdm=marker:

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"
