# Path to my bash configuration files
export BASHDIR=$HOME/dotfiles/bash/

# load default bash settings
if [ -f $BASHDIR/default.bashrc ]; then
    . $BASHDIR/default.bashrc
fi

# load personal bash settings
if [ -f $BASHDIR/after.bashrc ]; then
    . $BASHDIR/after.bashrc
fi

# ----------------------------------------------------------------
# other programs' settings may be appended to the end of this file

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"

